/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     系统内存管理函数
 *
 *            实现newlib/picolibc所需的底层内存分配函数（_sbrk）。
 *            具体信息请参考Newlib或Picolibc库手册。
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* 头文件包含 */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * 堆使用量的当前高水位指针
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief 为newlib堆分配内存，被malloc等C库函数调用
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib堆          #          MSP栈               #
 * #         #        #                         # 由_Min_Stack_Size保留        #
 * ############################################################################
 * ^-- RAM起始       ^-- _end                             _estack, RAM末尾 --^
 * @endverbatim
 *
 * 从链接脚本的'_end'符号处开始分配内存。
 * '_Min_Stack_Size'符号为MSP栈保留空间。
 * '_estack'符号为RAM末尾。
 * 注意：如果MSP栈在运行时超过保留大小，请增大'_Min_Stack_Size'。
 *
 * @param incr 要分配的内存大小（字节）
 * @return 分配的内存指针，失败返回(void*)-1
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end;            /* 链接脚本中定义的符号 */
  extern uint8_t _estack;         /* 链接脚本中定义的符号 */
  extern uint32_t _Min_Stack_Size; /* 链接脚本中定义的符号 */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* 首次调用时初始化堆末尾指针 */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* 防止堆增长侵入MSP栈保留区域 */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  /* Picolibc要求系统调用不带下划线前缀 */
  /* 创建强别名，使sbrk()调用解析到_sbrk()实现 */
  __strong_reference(_sbrk, sbrk);
#endif
